CREATE TABLE BUILDING_TYPE (
    id IDENTITY PRIMARY KEY,
    [name] NVARCHAR(100) UNIQUE,
    crypto_cost INT DEFAULT 0 NOT NULL,
    crypto_production INT DEFAULT 0 NOT NULL
);

CREATE TABLE BUILDING_RESOURCE_NET_MAINTENANCE_COST (
    building_type_id REFERENCES BUILDING_TYPE(id),
    resource_id REFERENCES [RESOURCE](id),
    PRIMARY KEY (building_id, resource_id),
    net_cost INT NOT NULL -- NEGATIVE NUMBER IS MAINTENACE COST, POSITIVE NUMBER IS INTERPRETED AS PRODUCTION!
);

CREATE TABLE BUILDING (
    id IDENTITY PRIMARY KEY,
    building_type_id REFERENCES BUILDING(id),
    system_id REFERENCES [SYSTEM](id)
);