CREATE TABLE BUILDING_TYPE (
    id INT IDENTITY PRIMARY KEY,
    [name] NVARCHAR(100) UNIQUE,
    crypto_cost INT DEFAULT 0 NOT NULL,
    crypto_production INT DEFAULT 0 NOT NULL,
    agent_buildable BOOLEAN NOT NULL
);

CREATE TABLE BUILDING_RESOURCE_NET_MAINTENANCE_COST (
    building_type_id INT REFERENCES BUILDING_TYPE(id),
    resource_id INT REFERENCES [RESOURCE](id),
    PRIMARY KEY (building_type_id, resource_id),
    net_cost INT NOT NULL -- NEGATIVE NUMBER IS MAINTENACE COST, POSITIVE NUMBER IS INTERPRETED AS PRODUCTION!
);

CREATE TABLE BUILDING (
    id INT IDENTITY PRIMARY KEY,
    building_type_id INT REFERENCES BUILDING(id),
    system_id INT REFERENCES [SYSTEM](id),
    agent_owner INT REFERENCES AGENT(id) -- IF NULL, THEN THE BUILDABLE IS OWNED BY THE SYSTEM!
);