pr: none
trigger:
  batch: true
  branches:
    include:
    - feature/*
    - main
  paths:
    include:
    - python-tick-script

jobs:
- job: BuildAndPush
  displayName: Docker build and push
  pool:
    name: Azure Pipelines
  steps:
  - task: Docker@2
    displayName: BuildAndPush
    inputs:
      command: buildAndPush
      repository: jakepelter/galactica-online-ticker
      dockerfile: python-tick-script/src/Dockerfile
      containerRegistry: 'jakep-dockerhub'
      tags: $(Build.BuildId)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: python-tick-script/charts
      artifactName: 'drop'