-- SCHEMA PREFIXED BECAUSE USUALLY RUN WITH MICROSOFT ENTRA LOGIN, NOT SCHEMA OWNER LOGIN
DROP TABLE galactica_dev.SHIP_CARGO;
DROP TABLE galactica_dev.SHIP;
DROP TABLE galactica_dev.SHIP_RESOURCE_NET_MAINTENANCE_COST;
DROP TABLE galactica_dev.SHIP_TYPE;

DROP TABLE galactica_dev.BUILDING;
DROP TABLE galactica_dev.BUILDING_RESOURCE_NET_MAINTENANCE_COST;
DROP TABLE galactica_dev.BUILDING_TYPE;

DROP TABLE galactica_dev.SYSTEM_RESOURCE_STOCKPILE;
DROP TABLE galactica_dev.[RESOURCE];
DROP TABLE galactica_dev.[SYSTEM];
DROP TABLE galactica_dev.AGENT;

DROP TABLE galactica_dev.DATABASECHANGELOG;
DROP TABLE galactica_dev.DATABASECHANGELOGLOCK;