pr: none
trigger:
  batch: true
  branches:
    include:
    - feature/*
    - main
  paths:
    include:
    - react-frontend

jobs:
- job: BuildAndPush
  displayName: Docker build and push
  pool:
    name: Azure Pipelines
  steps:
  - task: Docker@2
    displayName: BuildAndPush
    inputs:
      command: buildAndPush
      repository: jakepelter/galactica-online-website
      dockerfile: react-frontend/Dockerfile
      containerRegistry: 'jakep-dockerhub'
      tags: $(Build.BuildId)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: react-frontend/charts
      artifactName: 'drop'